import { Injectable } from '@angular/core';

export interface GalleryItem {
  src: string;
  alt: string;
  title: string;
  style: string;
  wallSystem: string;
  tile: string;
  finish: string;
  features: string[];
}

@Injectable({ providedIn: 'root' })
export class GalleryService {
  readonly items: GalleryItem[] = [
    // {
    //   src: 'assets/baths/1.jpg',
    //   alt: 'Marble Luxe Walk-in Shower',
    //   title: 'Marble Luxe Walk-in',
    //   style: 'Contemporary',
    //   wallSystem: 'Sentrel Stone Series',
    //   tile: 'Large Format Porcelain',
    //   finish: 'Calacatta White',
    //   features: ['Walk-in Shower', 'Rainfall Showerhead', 'Frameless Glass Door', 'Built-in Niche'],
    // },
    {
      src: 'assets/baths/2.jpg',
      alt: 'Coastal Grey Escape Shower',
      title: 'Coastal Grey Escape',
      style: 'Minimalist',
      wallSystem: 'SimTile',
      tile: 'Mosaic Accent Tile',
      finish: 'Veincut Grey',
      features: ['Corner Shower', 'Sliding Glass Door', 'Chrome Fixtures', 'Floating Shelf'],
    },
    {
      src: 'assets/baths/4.jpg',
      alt: 'Modern Soaking Suite Bathroom',
      title: 'Modern Soaking Suite',
      style: 'Modern',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Subway Tile Accent',
      finish: 'White Pearl',
      features: ['Freestanding Tub', 'Matte Black Fixtures', 'Separate Shower', 'Heated Floor'],
    },
    {
      src: 'assets/baths/5.jpg',
      alt: 'Classic Alcove Revival Bathroom',
      title: 'Classic Alcove Revival',
      style: 'Classic',
      wallSystem: 'Dimensions SimTile',
      tile: 'Ceramic Mosaic Floor',
      finish: 'Frost',
      features: ['Alcove Tub-Shower', 'Polished Chrome', 'Mosaic Accent Strip', 'Standard Door'],
    },
    {
      src: 'assets/baths/6.jpg',
      alt: 'Slate Contemporary Shower',
      title: 'Slate Contemporary',
      style: 'Contemporary',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Slate-Look Tile',
      finish: 'Dark Charcoal',
      features: ['Walk-in Shower', 'Linear Drain', 'Matte Black Hardware', 'Glass Panel'],
    },
    {
      src: 'assets/baths/7.jpg',
      alt: 'Farmhouse Warmth Bathroom',
      title: 'Farmhouse Warmth',
      style: 'Farmhouse',
      wallSystem: 'SimTile',
      tile: 'Penny Round Floor Tile',
      finish: 'Cotton White',
      features: ['Walk-in Shower', 'Brushed Nickel', 'Wood Accents', 'Open Shelving'],
    },
    {
      src: 'assets/baths/8.jpg',
      alt: 'Spa Walk-in Retreat Shower',
      title: 'Spa Walk-in Retreat',
      style: 'Modern',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Large Format Porcelain',
      finish: 'Warm Beige',
      features: ['Walk-in Shower', 'Steam-Ready', 'Bench Seat', 'Dual Showerheads'],
    },
    {
      src: 'assets/baths/9.jpg',
      alt: 'Barrier-Free Conversion Shower',
      title: 'Barrier-Free Conversion',
      style: 'Transitional',
      wallSystem: 'Dimensions SimTile',
      tile: 'Mosaic Floor Tile',
      finish: 'Classic White',
      features: ['Barrier-Free Entry', 'Handheld Shower', 'Grab Bar', 'Walk-in Access'],
    },
    {
      src: 'assets/baths/10.jpg',
      alt: 'Travertine Elegance Shower',
      title: 'Travertine Elegance',
      style: 'Classic',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Travertine-Look Tile',
      finish: 'Creme Travertine',
      features: ['Walk-in Shower', 'Niche Shelving', 'Oil-Rubbed Bronze', 'Half-Wall Glass'],
    },
    {
      src: 'assets/baths/11.jpg',
      alt: 'Midnight Sanctuary Bathroom',
      title: 'Midnight Sanctuary',
      style: 'Modern',
      wallSystem: 'SimTile',
      tile: 'Hex Floor Tile',
      finish: 'Bardiglio',
      features: ['Freestanding Tub', 'Brushed Gold Fixtures', 'Statement Accent Wall', 'Open Shelving'],
    },
    {
      src: 'assets/baths/12.jpg',
      alt: 'Crisp White Classic Shower',
      title: 'Crisp White Classic',
      style: 'Classic',
      wallSystem: 'Dimensions SimTile',
      tile: 'Hex Floor Tile',
      finish: 'Bright White',
      features: ['Alcove Shower', 'Polished Chrome', 'Classic Aesthetic', 'Standard Door'],
    },
    {
      src: 'assets/baths/13.jpg',
      alt: 'Rustic Stone Escape Bathroom',
      title: 'Rustic Stone Escape',
      style: 'Farmhouse',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Slate Mosaic Accents',
      finish: 'Natural Stone',
      features: ['Walk-in Shower', 'Pebble Floor Insert', 'Oil-Rubbed Bronze', 'Wood Accents'],
    },
    {
      src: 'assets/baths/14.jpg',
      alt: 'Minimalist Zen Shower',
      title: 'Minimalist Zen',
      style: 'Minimalist',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Large Format Tile',
      finish: 'Gray Quartz',
      features: ['Walk-in Shower', 'Frameless Glass', 'Linear Drain', 'Single-Handle Fixture'],
    },
    {
      src: 'assets/baths/15.jpg',
      alt: 'Bold Geometric Shower',
      title: 'Bold Geometric',
      style: 'Contemporary',
      wallSystem: 'SimTile',
      tile: 'Herringbone Floor',
      finish: 'Mocha Travertine',
      features: ['Walk-in Shower', 'Decorative Niche', 'Matte Black', 'Statement Floor'],
    },
    {
      src: 'assets/baths/16.jpg',
      alt: 'Transitional Two-Tone Bathroom',
      title: 'Transitional Two-Tone',
      style: 'Transitional',
      wallSystem: 'Dimensions SimTile',
      tile: 'Classic Tile',
      finish: 'White & Gray',
      features: ['Tub-Shower Combo', 'Polished Chrome', 'Wainscot Tiles', 'Standard Door'],
    },
    {
      src: 'assets/baths/17.jpg',
      alt: 'Luxe Master Retreat Bathroom',
      title: 'Luxe Master Retreat',
      style: 'Modern',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Veined Marble-Look',
      finish: 'Calacatta White',
      features: ['Walk-in Shower', 'Rainfall + Body Jets', 'Frameless Glass', 'Heated Floor'],
    },
    // {
    //   src: 'assets/baths/18.jpg',
    //   alt: 'Coastal Blue Haven Shower',
    //   title: 'Coastal Blue Haven',
    //   style: 'Contemporary',
    //   wallSystem: 'SimTile',
    //   tile: 'Pebble Floor Accent',
    //   finish: 'Azzurra Bay',
    //   features: ['Walk-in Shower', 'Pebble Floor', 'Brushed Nickel', 'Coastal Accents'],
    // },
    {
      src: 'assets/baths/20.jpg',
      alt: 'Industrial Modern Shower',
      title: 'Industrial Modern',
      style: 'Modern',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Concrete-Look Large Format',
      finish: 'Gray Quartz',
      features: ['Walk-in Shower', 'Floating Bench', 'Matte Black', 'Open Concept'],
    },
    {
      src: 'assets/baths/21.jpg',
      alt: 'Rose Gold and Marble Bathroom',
      title: 'Rose Gold & Marble',
      style: 'Contemporary',
      wallSystem: 'SimTile',
      tile: 'Marble Mosaic',
      finish: 'White Pearl',
      features: ['Freestanding Tub', 'Champagne Gold Fixtures', 'Statement Wall', 'Decorative Mirror'],
    },
    {
      src: 'assets/baths/22.jpg',
      alt: 'Timeless Subway Bathroom',
      title: 'Timeless Subway',
      style: 'Classic',
      wallSystem: 'Dimensions SimTile',
      tile: 'Classic Subway',
      finish: 'Bright White',
      features: ['Alcove Tub-Shower', 'Chrome Fixtures', 'Penny Round Floor', 'Simple Elegance'],
    },
    {
      src: 'assets/baths/23.jpg',
      alt: 'Desert Warmth Shower',
      title: 'Desert Warmth',
      style: 'Transitional',
      wallSystem: 'Sentrel Stone Series',
      tile: 'Sandstone Large Format',
      finish: 'Lincoln Gold',
      features: ['Walk-in Shower', 'Wood-Look Accents', 'Brushed Nickel', 'Open Niche'],
    },
    {
      src: 'assets/baths/24.jpg',
      alt: 'Champagne Glam Bathroom',
      title: 'Champagne Glam',
      style: 'Contemporary',
      wallSystem: 'SimTile',
      tile: 'Champagne Mosaic',
      finish: 'Botticino Cream',
      features: ['Freestanding Tub', 'Champagne Gold Fixtures', 'Accent Tile Wall', 'Vessel Sink'],
    },
  ];
}
